"""
ATSify Premium Resume Templates
12 curated recruiter-grade resume designs.
Each template has a distinct visual identity.
"""

TEMPLATES = {
    "executive_elite": {
        "id": "executive_elite",
        "name": "Executive Elite",
        "font_docx": "Garamond",
        "font_pdf": "Times-Roman",
        "primary_color": "#1e3a8a",
        "text_color": "#1e293b",
        "bg_color": "#ffffff",
        "layout": "two_column_sidebar",
        "margin": 0.85,
        "section_order": ["summary", "experience", "education", "skills", "projects", "certifications"],
        "recommended_role": "C-Suite, VPs, Directors",
        "category": "executive",
        "description": "Luxury corporate feel with navy accent, refined serif typography.",
        "badge": "Premium",
        "accent_bar": "#1e3a8a",
        "thumb_font": "serif",
        "base_scores": {"ats": 96, "visual": 93, "recruiter": 97, "readability": 95, "keyword": 90}
    },
    "modern_tech": {
        "id": "modern_tech",
        "name": "Modern Tech",
        "font_docx": "Arial",
        "font_pdf": "Helvetica",
        "primary_color": "#2563eb",
        "text_color": "#1e293b",
        "bg_color": "#ffffff",
        "layout": "single_column",
        "margin": 0.75,
        "section_order": ["summary", "experience", "skills", "projects", "education", "certifications"],
        "recommended_role": "Software Engineers, Data Scientists",
        "category": "tech",
        "description": "Clean minimal design with blue accent, optimized for FAANG screening.",
        "badge": "FAANG Style",
        "accent_bar": "#2563eb",
        "thumb_font": "sans-serif",
        "base_scores": {"ats": 95, "visual": 94, "recruiter": 92, "readability": 96, "keyword": 93}
    },
    "harvard_professional": {
        "id": "harvard_professional",
        "name": "Harvard Professional",
        "font_docx": "Times New Roman",
        "font_pdf": "Times-Roman",
        "primary_color": "#111827",
        "text_color": "#111827",
        "bg_color": "#ffffff",
        "layout": "single_column",
        "margin": 0.80,
        "section_order": ["summary", "experience", "education", "skills", "projects", "certifications"],
        "recommended_role": "All roles – highest ATS compatibility",
        "category": "ats",
        "description": "Classic academic styling with subtle gray accents, maximum parsing score.",
        "badge": "ATS Max",
        "accent_bar": "#111827",
        "thumb_font": "serif",
        "base_scores": {"ats": 99, "visual": 85, "recruiter": 90, "readability": 97, "keyword": 95}
    },
    "startup_founder": {
        "id": "startup_founder",
        "name": "Startup Founder",
        "font_docx": "Arial",
        "font_pdf": "Helvetica",
        "primary_color": "#d97706",
        "text_color": "#1e293b",
        "bg_color": "#ffffff",
        "layout": "two_column_sidebar",
        "margin": 0.70,
        "section_order": ["summary", "experience", "projects", "skills", "education", "certifications"],
        "recommended_role": "Founders, CEOs, Product Leads",
        "category": "startup",
        "description": "Bold orange accent, side-bar layout emphasizing impact and founder vibe.",
        "badge": "Bold",
        "accent_bar": "#d97706",
        "thumb_font": "sans-serif",
        "base_scores": {"ats": 92, "visual": 96, "recruiter": 95, "readability": 90, "keyword": 88}
    },
    "product_designer": {
        "id": "product_designer",
        "name": "Product Designer",
        "font_docx": "Arial",
        "font_pdf": "Helvetica",
        "primary_color": "#e60023",
        "text_color": "#1e293b",
        "bg_color": "#ffffff",
        "layout": "two_column_sidebar",
        "margin": 0.68,
        "section_order": ["summary", "skills", "projects", "experience", "education", "certifications"],
        "recommended_role": "Designers, UX/UI, Creative",
        "category": "creative",
        "description": "Vibrant red accent with creative sidebar, modern typography and layout.",
        "badge": "Creative",
        "accent_bar": "#e60023",
        "thumb_font": "sans-serif",
        "base_scores": {"ats": 88, "visual": 98, "recruiter": 93, "readability": 89, "keyword": 86}
    },
    "nordic_minimal": {
        "id": "nordic_minimal",
        "name": "Nordic Minimal",
        "font_docx": "Arial",
        "font_pdf": "Helvetica",
        "primary_color": "#475569",
        "text_color": "#334155",
        "bg_color": "#ffffff",
        "layout": "single_column",
        "margin": 0.90,
        "section_order": ["summary", "experience", "education", "skills", "projects", "certifications"],
        "recommended_role": "Architects, Minimalists, Writers",
        "category": "minimal",
        "description": "Scandinavian design emphasizing spacious whitespace and visual balance.",
        "badge": "Nordic",
        "accent_bar": "#475569",
        "thumb_font": "sans-serif",
        "base_scores": {"ats": 94, "visual": 95, "recruiter": 91, "readability": 97, "keyword": 89}
    },
    "timeline_pro": {
        "id": "timeline_pro",
        "name": "Timeline Pro",
        "font_docx": "Arial",
        "font_pdf": "Helvetica",
        "primary_color": "#0d9488",
        "text_color": "#1e293b",
        "bg_color": "#ffffff",
        "layout": "single_column",
        "margin": 0.78,
        "section_order": ["summary", "experience", "skills", "projects", "education", "certifications"],
        "recommended_role": "Project Managers, Operations",
        "category": "modern",
        "description": "Vertical timeline styling highlighting rapid career progression.",
        "badge": "Structured",
        "accent_bar": "#0d9488",
        "thumb_font": "sans-serif",
        "base_scores": {"ats": 93, "visual": 96, "recruiter": 94, "readability": 93, "keyword": 91}
    },
    "magazine_cv": {
        "id": "magazine_cv",
        "name": "Magazine CV",
        "font_docx": "Georgia",
        "font_pdf": "Times-Roman",
        "primary_color": "#881337",
        "text_color": "#1e293b",
        "bg_color": "#ffffff",
        "layout": "single_column",
        "margin": 0.82,
        "section_order": ["summary", "experience", "projects", "education", "skills", "certifications"],
        "recommended_role": "Editorial, Marketing, PR Specialists",
        "category": "editorial",
        "description": "Editorial layout with high-impact serif headers and wide columns.",
        "badge": "Editorial",
        "accent_bar": "#881337",
        "thumb_font": "serif",
        "base_scores": {"ats": 91, "visual": 97, "recruiter": 93, "readability": 92, "keyword": 87}
    },
    "split_vision": {
        "id": "split_vision",
        "name": "Split Vision",
        "font_docx": "Arial",
        "font_pdf": "Helvetica",
        "primary_color": "#065f46",
        "text_color": "#1e293b",
        "bg_color": "#ffffff",
        "layout": "two_column_sidebar",
        "margin": 0.70,
        "section_order": ["summary", "experience", "education", "skills", "projects", "certifications"],
        "recommended_role": "Consultants, Analysts, Corporate Leads",
        "category": "split",
        "description": "Bold 30/70 split background layout balancing details and achievements.",
        "badge": "Split View",
        "accent_bar": "#065f46",
        "thumb_font": "sans-serif",
        "base_scores": {"ats": 93, "visual": 95, "recruiter": 96, "readability": 91, "keyword": 90}
    },
    "metro_resume": {
        "id": "metro_resume",
        "name": "Metro Resume",
        "font_docx": "Arial",
        "font_pdf": "Helvetica",
        "primary_color": "#7c3aed",
        "text_color": "#1e293b",
        "bg_color": "#ffffff",
        "layout": "single_column",
        "margin": 0.75,
        "section_order": ["summary", "experience", "skills", "projects", "education", "certifications"],
        "recommended_role": "Product Managers, Engineers, Consultants",
        "category": "grid",
        "description": "Block-based design providing clear visual compartments and layout density.",
        "badge": "Grid Blocks",
        "accent_bar": "#7c3aed",
        "thumb_font": "sans-serif",
        "base_scores": {"ats": 94, "visual": 94, "recruiter": 93, "readability": 95, "keyword": 92}
    },
    "dark_executive": {
        "id": "dark_executive",
        "name": "Dark Executive",
        "font_docx": "Garamond",
        "font_pdf": "Times-Roman",
        "primary_color": "#b45309",
        "text_color": "#1e293b",
        "bg_color": "#ffffff",
        "layout": "single_column",
        "margin": 0.80,
        "section_order": ["summary", "experience", "education", "skills", "projects", "certifications"],
        "recommended_role": "Executives, Managing Directors, Partners",
        "category": "executive",
        "description": "Luxury gold accent layout featuring an elegant dark executive header.",
        "badge": "Gold Accent",
        "accent_bar": "#b45309",
        "thumb_font": "serif",
        "base_scores": {"ats": 92, "visual": 97, "recruiter": 96, "readability": 93, "keyword": 89}
    },
    "elite_portfolio": {
        "id": "elite_portfolio",
        "name": "Elite Portfolio",
        "font_docx": "Georgia",
        "font_pdf": "Times-Roman",
        "primary_color": "#78350f",
        "text_color": "#1e293b",
        "bg_color": "#ffffff",
        "layout": "two_column_sidebar",
        "margin": 0.72,
        "section_order": ["summary", "skills", "experience", "projects", "education", "certifications"],
        "recommended_role": "VPs, Creative Directors, Consultants",
        "category": "creative",
        "description": "Sophisticated layout optimized for profile photos and structural accents.",
        "badge": "Circular Photo",
        "accent_bar": "#78350f",
        "thumb_font": "serif",
        "base_scores": {"ats": 90, "visual": 98, "recruiter": 94, "readability": 91, "keyword": 87}
    }
}
